Задание 1
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк
и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6,
8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива
Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [4]:
pip install numpy

In [50]:
import numpy as np
import statistics

In [110]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])

In [74]:
print(a)
print("Размерность а: {}".format(a.ndim))
print("Формат а: {}".format(a.shape))

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Размерность а: 2
Формат а: (5, 2)


In [78]:
type(a)

numpy.ndarray

In [80]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [60]:
a1 = np.matrix('1 6; 2 8; 3 11; 3 10; 1 7')
print(a1)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [62]:
type(a1)

numpy.matrix

In [64]:
a1 = np.array(a1)

In [68]:
mean_a1 = a1.mean(axis=0)
mean_a1

array([2. , 8.4])

Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения
соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно
производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [84]:
a_centered = np.array(a-mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна
получиться величина _centered_spa. Затем поделите a_centered_sp на N-1, где N - число
наблюдений.

In [96]:
a1 = a_centered[:,0]
a2 = a_centered[:,1]
a_centered_sp = np.dot(a1,a2)
a_centered_sp

8.0

In [116]:
g = a.shape[0]
g

5

In [120]:
boc = a_centered_sp/(g-1)
boc

2.0

Задание 4.
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с
помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать
транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером
2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом
1.

In [122]:
a_T = a.T
a_T

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [124]:
j = np.cov(a_T)
j

array([[1. , 2. ],
       [2. , 4.3]])

In [132]:
a3 = j[0][1]
a3

2.0

Тема “Работа с данными в Pandas”

Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со
столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и
['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно
содержатся данные:
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и
поклонники']
Нужны prices!
[500, 400, 300, 350, 450, 600, 200]

In [142]:
import pandas as pd

In [148]:
authors = pd.DataFrame({'author_id': [1, 2, 3],
                       'author_name': ['Тургенев', 'Чехов', 'Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [158]:
books = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3],
                    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'prices': [500, 400, 300, 350, 450, 600, 200]
})

books

author_id            book_title  prices
0          1           Отцы и дети     500
1          1                 Рудин     400
2          1     Дворянское гнездо     300
3          2      Толстый и тонкий     350
4          2       Дама с собачкой     450
5          3                 Гроза     600
6          3  Таланты и поклонники     200

Задание 2
Получите датафрейм authors_price, соединив дата фреймы authors и books по полю author_id.

In [162]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'outer' )
authors_price

author_id author_name            book_title  prices
0          1    Тургенев           Отцы и дети     500
1          1    Тургенев                 Рудин     400
2          1    Тургенев     Дворянское гнездо     300
3          2       Чехов      Толстый и тонкий     350
4          2       Чехов       Дама с собачкой     450
5          3  Островский                 Гроза     600
6          3  Островский  Таланты и поклонники     200

Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими
книгами.

In [174]:
top5 = authors_price.nlargest(5, 'prices')
top5

author_id author_name        book_title  prices
5          3  Островский             Гроза     600
0          1    Тургенев       Отцы и дети     500
4          2       Чехов   Дама с собачкой     450
1          1    Тургенев             Рудин     400
3          2       Чехов  Толстый и тонкий     350

Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat
должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя
цена на книги этого авора.

In [184]:
df1 = authors_price.groupby('author_name').agg({'prices': 'min'}).rename(columns={'prices':'min_price'})
df2 = authors_price.groupby('author_name').agg({'prices': 'max'}).rename(columns={'prices':'max_price'})
df3 = authors_price.groupby('author_name').agg({'prices': 'mean'}).rename(columns={'prices':'mean_price'})
authors_stat=pd.concat([df1, df2, df3], axis = 1)
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         200        600       400.0
Тургенев           300        500       400.0
Чехов              350        450       400.0